Get a listing of Webinars and Stationary events
EscolaLMS/API pull request #165
Opened 2022-03-30 08:40 UTC by mako321

2022-03-30 11:29 UTC, qunabu approved these changes

2022-03-30 12:06 UTC, pa-cholek commented on app/Http/Controllers/EventAPIController.php
> +        $result = new LengthAwarePaginator($events->forPage($page, $perPage), $events->count(), $perPage, $page, [
This retrieves all webinars and events and then extracts part of the returned collection and builds a paginator from it?

I think what we need to do instead, is to create a database view that represents searchable data in unified format, query that view, and return stuff from it using polymorphic relation.

There is a library for migrating views https://github.com/staudenmeir/laravel-migration-views

And we need a view that joins data from both tables using UNION
so something like
```
SELECT
webinars.id as event_id,
"EscolaLms\Webinars\Models\Webinar" as event_type,
webinars.active_from as start_date,
webinars.active_to as end_date,
UNION
SELECT 
stationary.id as event_id,
"EscolaLms\StationaryEvents\Models\StationaryEvent" as event_class,
stationary.start_date as start_date,
stationary.end_date as end_date,
```
etc, then query and paginate this view using Model (I'm pretty sure that we can just create a model that has $table='view_name' and it should work as if it was using a table) and that Model should have method
```
event(): MorphTo {
    return $this->morphTo()
} 
```
and then we need to just return JsonResource that extracts that morphed event data

I'm not sure if we ever did something like this but it's worth a try XD

2022-03-30 12:11 UTC, pa-cholek reviewed
This is not a scalable/efficient solution.

Alternatively to creating database view, we can just create a new table (`searchable_events`?) and Model; and insert data to this new table every time a Webinar or StationaryEvent is created (using listeners on webinar/stationary created event).
This table should have only id, event_id, event_type, and Model should have event():morphTo and then we can query it using whereHas('event', fn($query) => applycriteriatothisquery).

2022-03-30 12:54 UTC, HerbertIV approved these changes

2022-03-31 12:08 UTC, qunabu requested changes
please change as @pa-cholek suggests

2022-04-04 09:28 UTC, pa-cholek commented on app/Http/Resources/EventResource.php
> +            ? StationaryEventResource::make($event)
Shouldn't this be `StationaryEventResource::make($event)->toArray($request)`?

2022-04-04 09:51 UTC, pa-cholek approved these changes

2022-04-04 10:48 UTC, merged